### ISSUE TITLE
undefined method 'action' for Beaver

### ISSUE THREAD

**Issue by crusadergo** [jhollinger/beaver#10]
Hi there!

I ran the command today

`cat log/* | beaver --action=create`

, but got an error:

`/home/deployer/.rvm/gems/ruby-2.1.0/gems/beaver-1.4.4/lib/beaver/dam.rb:105:in `===': undefined method `action' for #<Beaver::Parsers::HTTP:0x000000019e7d88> (NoMethodError)
	from /home/deployer/.rvm/gems/ruby-2.1.0/gems/beaver-1.4.4/lib/beaver/beaver.rb:168:in `block in hit_dams'
	from /home/deployer/.rvm/gems/ruby-2.1.0/gems/beaver-1.4.4/lib/beaver/beaver.rb:167:in `each'
	from /home/deployer/.rvm/gems/ruby-2.1.0/gems/beaver-1.4.4/lib/beaver/beaver.rb:167:in `hit_dams'
	from /home/deployer/.rvm/gems/ruby-2.1.0/gems/beaver-1.4.4/lib/beaver/beaver.rb:116:in `block in stream'
	from /home/deployer/.rvm/gems/ruby-2.1.0/gems/beaver-1.4.4/lib/beaver/beaver.rb:206:in `call'
	from /home/deployer/.rvm/gems/ruby-2.1.0/gems/beaver-1.4.4/lib/beaver/beaver.rb:206:in `block in _parse'
	from /home/deployer/.rvm/gems/ruby-2.1.0/gems/beaver-1.4.4/lib/beaver/beaver.rb:223:in `each_line'
	from /home/deployer/.rvm/gems/ruby-2.1.0/gems/beaver-1.4.4/lib/beaver/beaver.rb:223:in `_parse'
	from /home/deployer/.rvm/gems/ruby-2.1.0/gems/beaver-1.4.4/lib/beaver/beaver.rb:115:in `stream'
	from /home/deployer/.rvm/gems/ruby-2.1.0/gems/beaver-1.4.4/lib/beaver/beaver.rb:38:in `stream'
	from /home/deployer/.rvm/gems/ruby-2.1.0/gems/beaver-1.4.4/bin/beaver:45:in `<top (required)>'
	from /home/deployer/.rvm/gems/ruby-2.1.0/bin/beaver:23:in `load'
	from /home/deployer/.rvm/gems/ruby-2.1.0/bin/beaver:23:in `<main>'
	from /home/deployer/.rvm/gems/ruby-2.1.0/bin/ruby_executable_hooks:24:in `eval'
	from /home/deployer/.rvm/gems/ruby-2.1.0/bin/ruby_executable_hooks:24:in `<main>'`

Is this an isolated case, or is there no such option anymore?

**Comment by jhollinger** [comment]
It's still an option, but only for Rails logs (as opposed to Nginx, Apache, Sidekiq, etc logs). Is it possible you have more than just Rails logs in your `log/` dir?
